Change is proxy configurationb
# dnf clean all ; dnf list
0 files removed
Yum Repository                                                                                                                 0.0  B/s |   0  B     00:00
Errors during downloading metadata for repository 'baseos':
  - Curl error (5): Couldn't resolve proxy name for http://test.com/rhel-8-for-x86_64-baseos-rpms/repodata/repomd.xml [Could not resolve proxy: _none_]
Error: Failed to download metadata for repo 'baseos': Cannot download repomd.xml: Curl error (5): Couldn't resolve proxy name for http://test.com/rhel-8-for-x86_64-baseos-rpms/repodata/repomd.xml [Could not resolve proxy: _none_]

yum.conf:

[main]
cachedir=/var/cache/yum/$basearch/$releasever
clean_requirements_on_remove=1
debuglevel=2
exactarch=1
gpgcheck=1
installonly_limit=5
keepcache=0
localpkg_gpgcheck=1
logfile=/var/log/yum.log
obsoletes=1
plugins=1
proxy=_none_  <-- entry causing issue

repo file:

[baseos]
name=Yum Repository
baseurl=http://test.com/rhel-8-for-x86_64-baseos-rpms
enabled=1
gpgcheck=0